### ISSUE TITLE
-lba option outsputs incorrect LBA for DA files

### ISSUE THREAD

**Issue by Kuumba123** [Lameguy64/mkpsxiso#32]
happens regardless if its via header or regular text file

**Comment by Lameguy64** [comment]
The LBA coordinates calculated for DA files look pretty valid to me. You have to consider that DA files are always placed after the data files as they are defined as audio tracks in which the LBA of DA files point to directly. Some games use DA files because the file entries contain an exact location for the audio track, as the CD-ROM controller only returns MM:SS rather than MM:SS:FF when obtaining track coordinates from it, which can cause playback issues in some circumstances.

You may also want to consider that the LBA points to the pregap of the track, so you'll have to add 150 sectors if you desire to skip the pregap when playing back a track from a DA file's LBA.

**Comment by Kuumba123** [comment]
alright fine , plus I kinda just relezied I can just use the cue file to get the LBA  . also one other thing . Not sure if this is just a simply oversight or something but how come you can't specify an abosulate file path for the sources in the xml files ?

**Comment by CookiePLMonster** [comment]
> but how come you can't specify an abosulate file path for the sources in the xml files ?

It works fine, at least for non-DA files - that's what I do in [GT2 Combined Disc](https://github.com/CookiePLMonster/GT2-Combined-Disc).

**Comment by Kuumba123** [comment]
however your tool gives me the completetly wrong LBA , currently Im working on MegaMan 8 and for the file END1.DA it will always return -559038737 in the C header it outputs (yes Im on the newest version). Theres also a bunch of other problems with this tool in regards to the digital audio but Im just gonna open that up in another issue

**Comment by Kuumba123** [comment]
let me be clear I just need the LBA of END1.DA that is included in the ISO9660 file system
