### ISSUE TITLE
Tomba! (USA) is missing 150 sectors

### ISSUE THREAD

**Issue by CookiePLMonster** [Lameguy64/mkpsxiso#44]
Reported via e-mail, not checked in detail but posting here so I don't forget - reportedly repacking **Tomba! (USA)** comes about 150 sectors short. It could be a data post-gap or something else.

**Comment by alex-free** [comment]
Does this game have CDDA? I noticed that if the game has CDDA tracks (and they are not referenced by .DA files) it doesn't do the pre-gap in the last part of the data track.

**Comment by alex-free** [comment]
Interesting, this game does not have CDDA according to http://redump.org/disc/8604/. I have encountered an issue before however where when dumping i.e. ridge racer Japan: http://redump.org/disc/2679/ there is no pre-gap between the data track and the CDDA because the CDDA are never referenced in the data track so it doesn't do the 'hack' to add it to the end of the data track like other games.
